spring:
  profiles:
    active: live
  datasource:
    url: jdbc:mariadb://localhost:3306/tasks?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    name: tasks
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: Task App

server:
  port: 8080